### PR TITLE
feat:added Product listing

### PR DESCRIPTION
**Pull request by Asuraking1n**

### CODE REVIEW

**Review by krgarima — COMMENTED** [review]
https://user-images.githubusercontent.com/90110521/155840133-e6313280-becb-49a5-88fe-e810879b3394.mp4

Wrong image displayed on hover.

**Review by krgarima — CHANGES_REQUESTED** [review]
Some suggestions:
1. Heading here should be 'Filter by price'
SIZE
2. Filter by Price and filter by rating can be added.

**Comment by Asuraking1n** [comment]
> Amayra.Mozilla.Firefox.2022-02-26.16-09-50.mp4 
> Wrong image displayed on hover.

Yes left on purpose....I thought I can change these data...from api....so...I didn't changed it here

**Comment by Asuraking1n** [comment]
> Some suggestions:
> 
> 1. Heading here should be 'Filter by price'
>    SIZE
> 2. Filter by Price and filter by rating are missing here.

I will fix this

**Review by sakshi006 — APPROVED** [review]
Looks good to me.

**Pull request merged**
